### ISSUE TITLE
Add support for Skipper ingress

### ISSUE THREAD

**Issue by MarcusNoble** [openfaas-incubator/ingress-operator#1]
Currently only the Nginx ingress controller is supported. It'd be good to provide support for others, in this case Skipper.

## Possible Solution

Example manual ingress:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-openfaas
  namespace: openfaas
  annotations:
    kubernetes.io/ingress.class: skipper
    zalando.org/skipper-filter: setPath("/function/hello-openfaas")
spec:
  rules:
    - host: hello-openfaas.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: gateway
              servicePort: 8080
```

## Context

We're not using Nginx controller in our clusters so wouldn't be able to leverage this controller. Currently we're manually creating ingress resources using the above example.

## Your Environment

* What version and distriubtion of Kubernetes are you using: 1.12

* What network driver are you using and what CIDR: Weave net
