### ISSUE TITLE
Customise Host Path

### ISSUE THREAD

**Issue by andrew-s** [openfaas-incubator/ingress-operator#18]
When defining the `FunctionIngress` you should be able to customise the host path, e.g. in a RESTful API you may want to map functions more logically (or if you were porting an existing application).

## Expected Behaviour
Path maps and routes correctly

## Current Behaviour
`FunctionIngress` only ever maps to `/(.*)` for each domain specified

## Possible Solution
Currently, the generated ingress looks like;

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-openfaas-io-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /function/openfaas-insiders/$1
  name: insiders-openfaas-io-tls
spec:
  rules:
  - host: insiders.openfaas.io
    http:
      paths:
      - backend:
          serviceName: gateway
          servicePort: 8080
        path: /(.*)
  tls:
  - hosts:
    - insiders.openfaas.io
    secretName: insiders-openfaas-io-tls-cert
```

However, for this particular use case the end result should look like;

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: api-app-profiles-create
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: "/function/profiles-view/$1"
        kubernetes.io/ingress.class: "ingress-api"
    namespace: openfaas
spec:
    tls:
    - hosts:
      - api.example.dev
      secretName: example-tls
    rules:
    - host: api.example.dev
      http:
        paths:
        - path: /v1/profiles/view/(.*)
          backend:
            serviceName: gateway
            servicePort: 8080
```

Through some form of annotation on the CRD filter up the; `spec.rules.host.http.paths.backend.path`

## Context
Provides RESTful *like* URI's through OF without the need for manually defining the ingress(s)
