### ISSUE TITLE
Test multiple paths for the same host

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/ingress-operator#21]
## Task

Test multiple paths for the same host

i.e. two function ingress entries as per the new feature in #20, but with the same domain and differing paths.

I.e. can we write two FunctionIngress records that would serve two separate back-end functions from the same sub-domain and TLS cert:

api.dx.no/v1/customers
api.dx.no/v1/tickets

```yaml
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: api.dx.no
  namespace: openfaas
spec:
  domain: "api.dx.no"
  function: "list-customers"
  ingressType: "nginx"
  path: "/v1/customers/(*.)"
    tls:
      enabled: true
      issuerRef:
         name: "letsencrypt-staging"
         kind: "Issuer"

---
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: api.dx.no
  namespace: openfaas
spec:
  domain: "api.dx.no"
  function: "list-tickets"
  ingressType: "nginx"
  path: "/v1/tickets/(*.)"
    tls:
      enabled: true
      issuerRef:
         name: "letsencrypt-staging"
         kind: "Issuer"
```

**Comment by alexellis** [comment]
These were my target URLs:

```
http://api.myfaas.club/v2/customers/100
http://api.myfaas.club/v1/customers/100
http://api.myfaas.club/v1/tickets/100
```

My stack.yml

```
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  customers:
    lang: go
    handler: ./customers
    image: alexellis2/customers:latest
  customers-v2:
    lang: go
    handler: ./customers-v2
    image: alexellis2/customers:2.0


  tickets:
    lang: go
    handler: ./tickets
    image: alexellis2/tickets:latest
```

My FNI:

```
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: tickets-api
  namespace: openfaas
spec:
  domain: "api.myfaas.club"
  function: "tickets"
  ingressType: "nginx"
  path: "/v1/tickets/(.*)"
  tls:
    enabled: false
---
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: customers-api
  namespace: openfaas
spec:
  domain: "api.myfaas.club"
  function: "customers"
  ingressType: "nginx"
  path: "/v1/customers/(.*)"
  tls:
    enabled: false
---
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: customers-api-v2
  namespace: openfaas
spec:
  domain: "api.myfaas.club"
  function: "customers-v2"
  ingressType: "nginx"
  path: "/v2/customers/(.*)"
  tls:
    enabled: false
```

It all worked as expected.
