### ISSUE TITLE
Nginx Ingress Annotations Not Applied

### ISSUE THREAD

**Issue by Janaka-Steph** [openfaas-incubator/ingress-operator#28]
Adding `nginx.ingress.kubernetes.io/from-to-www-redirect: "true"` annotations to FunctionIngress resources has no effect.

## Context
My function is a website that uses the dockerfile template and is served with Nginx. I am wondering if this Nginx is causing the annotation to not be applied

## Expected Behaviour
Expect annotations to be applied.

## Steps to Reproduce (for bugs)
Adding `from-to-www-redirect` annotation.
```
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: example
  namespace: openfaas
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
...
```
`kubectl apply -f fn_ingress.yml`

Note that I can see the annotation on functioningress resource.
```
$ kubectl describe functioningress.openfaas.com/example -n openfaas
Name:         example
Namespace:    openfaas
Labels:       <none>
Annotations:  nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
```

And also in the ingress resource. 
```
$ kubectl describe ing -n openfaas                                             
Name:             example
Namespace:        openfaas
...
Annotations:     cert-manager.io/issuer: letsencrypt-prod
                      com.openfaas.spec: {"metadata":{"name":"example","namespace":"openfaas"...
                      kubernetes.io/ingress.class: nginx
                      nginx.ingress.kubernetes.io/from-to-www-redirect: true
                      nginx.ingress.kubernetes.io/rewrite-target: /function/example/$1
```

## Your Environment
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alexellis** [comment]
Hi @Janaka-Steph thank you for putting together a detailed report. This is much appreciated.

Would you be willing to work on a patch for this?

Regards,

Alex

**Comment by alexellis** [comment]
I would probably suggest you use an alternative to `rewrite-target`, perhaps what you shared on Slack? The reason for this is that we do set specific rules for URL re-writing according to the way the FunctionIngress has been created.

**Comment by Janaka-Steph** [comment]
Ok I have modified the issue, sorry for the confusion. Hope it is clear now.
I would love to be able to contribute and patch it but I don't think my skills are good enough. :/

**Comment by aledbf** [comment]
@Janaka-Steph please post the ingress yaml. What are you trying to do?

This annotation only creates a new server block with a redirect. If the ingress host is www.foo.bar, it will create a server block with `server_name foo.bar` and any request to this host triggers a redirect to `www.foo.bar`

**Comment by Janaka-Steph** [comment]
@aledbf Thanks for the quick reply. I am hosting a website, which works well except I just need to redirect to www.

The ingress has been posted in the issue, but I here is to whole file. Or are you referring to an other file?
```
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: example
  namespace: openfaas
spec:
  domain: "example.com"
  function: "example"
  ingressType: "nginx"
  tls:
    enabled: true
    issuerRef:
      name: "letsencrypt-prod"
      kind: "Issuer"
```
